env: ENV_DEV
server:
  http:
    addr: 0.0.0.0:8000
    timeout: 1s
    real_ip:
      ip_headers: ["X-Real-IP", "X-Forwarded-For", "X-Client-IP"]
      trusted_proxies: []
      trusted_header: "X-Connecting-IP"
  grpc:
    addr: 0.0.0.0:9000
    timeout: 1s
data:
  database:
    driver: mysql
    addr: localhost:3306
    username: root
    password: password
    protocol: tcp
    schema: test
    params: "parseTime=True&loc=Local"
  redis:
    addr: 127.0.0.1:6379
    read_timeout: 0.2s
    write_timeout: 0.2s
    username:
    password:
    db: 0
observability:
  trace:
    endpoint: localhost:4317
    production_sample_rate: 0.1
  metrics:
    endpoint: localhost:4317
client:
  http:
    retry_count: 5
app:
